app = 'employee-jabber'
primary_region = 'ewr'

[build]

[env]

[processes]
  app = 'run --allow-net --allow-env --unstable-kv ./src/main.ts'

[http_service]
  internal_port = 8000
  force_https = true
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
