# fly.toml app configuration file generated for employee-jabber on 2025-05-26T09:09:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'employee-jabber'
primary_region = 'ewr'

[build]

[env]

[processes]
  app = 'run --allow-net --allow-env --unstable-kv ./src/main.ts'

[http_service]
  internal_port = 8000
  force_https = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
